src/Entity/Schedule.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ScheduleRepository")
 */
class Schedule
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    public $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $start_time_morning;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $end_time_morning;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $start_time_afternoon;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $end_time_afternoon;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visible;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $monday;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $tuesday;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $wednesday;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $thursday;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $friday;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $saturday;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $sunday;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Sector", mappedBy="schedule")
     */
    private $sector;

    public function __construct()
    {
        $this->sector = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartTimeMorning(): ?\DateTimeInterface
    {
        return $this->start_time_morning;
    }

    public function setStartTimeMorning(?\DateTimeInterface $start_time_morning): self
    {
        $this->start_time_morning = $start_time_morning;

        return $this;
    }

    public function getEndTimeMorning(): ?\DateTimeInterface
    {
        return $this->end_time_morning;
    }

    public function setEndTimeMorning(?\DateTimeInterface $end_time_morning): self
    {
        $this->end_time_morning = $end_time_morning;

        return $this;
    }

    public function getStartTimeAfternoon(): ?\DateTimeInterface
    {
        return $this->start_time_afternoon;
    }

    public function setStartTimeAfternoon(?\DateTimeInterface $start_time_afternoon): self
    {
        $this->start_time_afternoon = $start_time_afternoon;

        return $this;
    }

    public function getEndTimeAfternoon(): ?\DateTimeInterface
    {
        return $this->end_time_afternoon;
    }

    public function setEndTimeAfternoon(?\DateTimeInterface $end_time_afternoon): self
    {
        $this->end_time_afternoon = $end_time_afternoon;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    public function getMonday(): ?bool
    {
        return $this->monday;
    }

    public function setMonday(bool $monday): self
    {
        $this->monday = $monday;

        return $this;
    }

    public function getTuesday(): ?bool
    {
        return $this->tuesday;
    }

    public function setTuesday(bool $tuesday): self
    {
        $this->tuesday = $tuesday;

        return $this;
    }

    public function getWednesday(): ?bool
    {
        return $this->wednesday;
    }

    public function setWednesday(bool $wednesday): self
    {
        $this->wednesday = $wednesday;

        return $this;
    }

    public function getThursday(): ?bool
    {
        return $this->thursday;
    }

    public function setThursday(bool $thursday): self
    {
        $this->thursday = $thursday;

        return $this;
    }

    public function getFriday(): ?bool
    {
        return $this->friday;
    }

    public function setFriday(bool $friday): self
    {
        $this->friday = $friday;

        return $this;
    }

    public function getSaturday(): ?bool
    {
        return $this->saturday;
    }

    public function setSaturday(bool $saturday): self
    {
        $this->saturday = $saturday;

        return $this;
    }

    public function getSunday(): ?bool
    {
        return $this->sunday;
    }

    public function setSunday(bool $sunday): self
    {
        $this->sunday = $sunday;

        return $this;
    }

    /**
     * @return Collection|Sector[]
     */
    public function getSector(): Collection
    {
        return $this->sector;
    }

    public function addSector(Sector $sector): self
    {
        if (!$this->sector->contains($sector)) {
            $this->sector[] = $sector;
            $sector->setSchedule($this);
        }

        return $this;
    }

    public function removeSector(Sector $sector): self
    {
        if ($this->sector->contains($sector)) {
            $this->sector->removeElement($sector);
            // set the owning side to null (unless already changed)
            if ($sector->getSchedule() === $this) {
                $sector->setSchedule(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

}

src/Form/ScheduleType.php
<?php

namespace App\Form;

use App\Entity\Schedule;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ScheduleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, array('label' => "Nombre",'attr' => array('maxlength' => '20', 'rows' => '1','required' => true, 'resize' => 'none')))
    
            ->add('description', TextAreaType::class, array('label' => "Descripcion",'attr' => array('maxlength' => '200', 'rows' => '1','required' => true)))
            ->add('start_time_morning', TimeType::class, array('label' => "Hora de inicio por la mañana", 'placeholder' => '' ,'required' => false))
            ->add('end_time_morning', TimeType::class, array('label' => "Hora de fin por la mañana", 'placeholder' => '' ,'required' => false))
            ->add('start_time_afternoon', TimeType::class, array('label' => "Hora de inicio por la tarde", 'placeholder' => '' ,'required' => false))
            ->add('end_time_afternoon', TimeType::class, array('label' => "Hora de fin por la tarde", 'placeholder' => '' ,'required' => false))
            // ->add('visible')
            ->add('monday', CheckboxType::class, array('label' => "Lunes " ,'required' => false))
            ->add('tuesday', CheckboxType::class, array('label' => "Martes " ,'required' => false))
            ->add('wednesday', CheckboxType::class, array('label' => "Miercoles " ,'required' => false))
            ->add('thursday', CheckboxType::class, array('label' => "Jueves " ,'required' => false))
            ->add('friday', CheckboxType::class, array('label' => "Viernes " ,'required' => false))
            ->add('saturday', CheckboxType::class, array('label' => "Sabado " ,'required' => false))
            ->add('sunday', CheckboxType::class, array('label' => "Domingo " ,'required' => false))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Schedule::class,
        ]);
    }
}

src/Controller/ScheduleController.php
<?php

namespace App\Controller;

use App\Entity\Schedule;
use App\Form\ScheduleType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Swift_Mailer;

class ScheduleController extends AbstractController
{
     /**
     * @Route("/schedule", name="schedule")
     */
    public function index()
    {
        return $this->render('schedule/index.html.twig', [
            'controller_name' => 'ScheduleController',
        ]);
    }

     /**
     * @Route("/new", name="schedule_new", methods={"GET","POST"})
     */
    public function new(Request $request,Swift_Mailer $mailer ): Response
    {
        // MailerInterface $mailer
        $schedule = new Schedule();
        $form = $this->createForm(ScheduleType::class, $schedule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //COMPROBAR DIFERENCIA DE HORAS
            $init_morning=$request->request->get("start_time_morning");
            $final_morning=$request->request->get("end_time_morning");
           // $hora1 = strtotime( $init_morning );
            //$hora2 = strtotime( $final_morning );
           
            $entityManager = $this->getDoctrine()->getManager();
            $schedule->setVisible(false);
            $schedule->setDescription("Sin aprobar");
            $entityManager->persist($schedule);
            $entityManager->flush();

            // ENVIA UN CORREO AL ADMINISTRADOR PARA NOTIFICARLE QUE HAY UNA PROPUESTA 
            
             $mensaje="Hay un nueva propuesta de horario";
             $micorreo="facilriego@gmail.com";
                //Enviar correo
                $message = (new \Swift_Message('Nueva Solicitud de Horario'))
                ->setFrom($micorreo)
                ->setTo("jaimenavarrol97@gmail.com")
                ->setBody("Hay una neuva solicitud de horario");
    
                $mailer->send($message);





            return $this->redirectToRoute('main');
            
        }

        return $this->render('schedule/new.html.twig', [
            'schedule' => $schedule,
            'form' => $form->createView(),
        ]);
    }
}

templates/schedule/_delete_form.html.twig
<form method="post" action="{{ path('schedule_delete', {'id': schedule.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ schedule.id) }}">
    <button class="btn">Delete</button>
</form>

templates/schedule/_form.html.twig
{% extends 'base.html.twig' %}


{% block body %}
{{ form_start(form) }}
{{ form_widget(form) }}


{# {{ form_start(form) }}
{{form_label(form.name)}}
{{ form_widget(form.name,{'attr':{'id':'name'}}) }}

{{form_label(form.description)}}
{{ form_widget(form.description,{'attr':{'id':'description'}}) }}

{{form_label(form.start_time_morning)}}
{{ form_widget(form.start_time_morning,{'attr':{'id':'start_time_morning'}}) }}

{{form_label(form.end_time_morning)}}
{{ form_widget(form.end_time_morning,{'attr':{'id':'end_time_morning'}}) }}

{{form_label(form.start_time_afternoon)}}
{{ form_widget(form.start_time_afternoon,{'attr':{'id':'start_time_afternoon'}}) }}

{{form_label(form.end_time_afternoon)}}
{{ form_widget(form.end_time_afternoon,{'attr':{'id':'end_time_afternoon'}}) }}

{{form_label(form.monday)}}
{{ form_widget(form.monday,{'attr':{'id':'monday'}}) }}

{{form_label(form.tuesday)}}
{{ form_widget(form.tuesday,{'attr':{'id':'tuesday'}}) }}

{{form_label(form.wednesday)}}
{{ form_widget(form.wednesday,{'attr':{'id':'wednesday'}}) }}

{{form_label(form.thursday)}}
{{ form_widget(form.thursday,{'attr':{'id':'thursday'}}) }}

{{form_label(form.friday)}}
{{ form_widget(form.friday,{'attr':{'id':'friday'}}) }}

{{form_label(form.saturday)}}
{{ form_widget(form.saturday,{'attr':{'id':'saturday'}}) }}

{{form_label(form.sunday)}}
{{ form_widget(form.sunday,{'attr':{'id':'sunday'}}) }}



    <button id="guardar">{{ button_label|default('Enviar') }}</button>
{{ form_end(form) }}
    <button id="salir" onclick="window.location.href='{{ path('main') }}'">Cancelar</button> #}

{% endblock %}

templates/schedule/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Schedule{% endblock %}

{% block body %}
    <h1>Edit Schedule</h1>

    {{ include('schedule/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('schedule_index') }}">back to list</a>

    {{ include('schedule/_delete_form.html.twig') }}
{% endblock %}

templates/schedule/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Historial de riegos{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

 {% include "navbar/schedulenavbar.html.twig" %} 


<div class="container" id="tableArea">


{% endblock %}

templates/schedule/new.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap.css') }}" />
    <link href="{{ asset('css/style.css') }}" rel="stylesheet" />
{% endblock %}

{% block title %}Solicitar nuevo horario{% endblock %}

{% block body %}
    <h1>Solicitar horario</h1>
    
     {{ include('schedule/_form.html.twig') }} 

    
    

    <button id="guardar">{{ button_label|default('Enviar') }}</button>
{{ form_end(form) }}
    <button id="salir" onclick="window.location.href='{{ path('main') }}'">Cancelar</button>


{% endblock %}

templates/schedule/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Schedule{% endblock %}

{% block body %}
    <h1>Schedule</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ schedule.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ schedule.name }}</td>
            </tr>
            <tr>
                <th>Days</th>
                <td>{{ schedule.days ? schedule.days|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Start_time_morning</th>
                <td>{{ schedule.startTimeMorning ? schedule.startTimeMorning|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End_time_morning</th>
                <td>{{ schedule.endTimeMorning ? schedule.endTimeMorning|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Start_time_afternoon</th>
                <td>{{ schedule.startTimeAfternoon ? schedule.startTimeAfternoon|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End_time_afternoon</th>
                <td>{{ schedule.endTimeAfternoon ? schedule.endTimeAfternoon|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Visible</th>
                <td>{{ schedule.visible ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('schedule_index') }}">back to list</a>

    <a href="{{ path('schedule_edit', {'id': schedule.id}) }}">edit</a>

    {{ include('schedule/_delete_form.html.twig') }}
{% endblock %}