src/Entity/History.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HistoryRepository")
 */
class History
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="time")
     */
    public $start_time;

    /**
     * @ORM\Column(type="time")
     */
    public $end_time;

    /**
     * @ORM\Column(type="integer")
     */
    public $start_humidity;

    /**
     * @ORM\Column(type="integer")
     */
    public $final_humidity;

    /**
     * @ORM\Column(type="integer")
     */
    public $total_liters;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Sector", inversedBy="histories")
     */
    private $sector;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->start_time;
        // return $this->start_time->format('H:i');
    }

    public function setStartTime(\DateTimeInterface $start_time): self
    {
        $this->start_time = $start_time;

        return $this;
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->end_time;
    }

    public function setEndTime(\DateTimeInterface $end_time): self
    {
        $this->end_time = $end_time;

        return $this;
        // return $this->end_time->format('H:i');
    }

    public function getStartHumidity(): ?int
    {
        return $this->start_humidity;
    }

    public function setStartHumidity(int $start_humidity): self
    {
        $this->start_humidity = $start_humidity;

        return $this;
    }

    public function getFinalHumidity(): ?int
    {
        return $this->final_humidity;
    }

    public function setFinalHumidity(int $final_humidity): self
    {
        $this->final_humidity = $final_humidity;

        return $this;
    }

    public function getTotalLiters(): ?int
    {
        return $this->total_liters;
    }

    public function setTotalLiters(int $total_liters): self
    {
        $this->total_liters = $total_liters;

        return $this;
    }

    public function getSector(): ?Sector
    {
        return $this->sector;
    }

    public function setSector(?Sector $sector): self
    {
        $this->sector = $sector;

        return $this;
    }

    public function __toString()
    {
        return $this->sector->getName();
    }
}

src/Form/HistoryType.php
<?php

namespace App\Form;

use App\Entity\History;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HistoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date')
            ->add('start_time')
            ->add('end_time')
            ->add('start_humidity')
            ->add('final_humidity')
            ->add('total_liters')
            ->add('sector')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => History::class,
        ]);
    }
}

src/Controller/HistoryController.php
<?php

namespace App\Controller;

use App\Entity\History;
use App\Entity\Sector;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HistoryController extends AbstractController
{
    /**
     * @Route("/history", name="history_index")
     */
    public function index()
    {
    
        $historyRepository = $this->getDoctrine()->getRepository(History::class);
        $histories = $historyRepository->findAll();

        $sectorRepository = $this->getDoctrine()->getRepository(Sector::class);
        $sectors = $sectorRepository->findAll();

        return $this->render('history/index.html.twig', [
            'sectors' => $sectors,
            'histories' => $histories,
            'user' => $this->getUser(),
        ]);

    }

}

templates/history/_delete_form.html.twig
<form method="post" action="{{ path('history_delete', {'id': history.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ history.id) }}">
    <button class="btn">Delete</button>
</form>

templates/history/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/history/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit History{% endblock %}

{% block body %}
    <h1>Edit History</h1>

    {{ include('history/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('history_index') }}">back to list</a>

    {{ include('history/_delete_form.html.twig') }}
{% endblock %}

templates/history/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Historial de riegos{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

 {% include "navbar/historynavbar.html.twig" %} 


<div class="containter">
	<div class="row-xs-12 row-sm-12 row-md-12 row-lg-12">
		<h1>Historial de riegos</h1>
	</div>
	<br>
	<table id="dtHorizontalExample" class="table table-responsive-xs" cellspacing="0" width="100%">
		<thead>
			<tr>
				<th>Nombre de sector</th>
				<th>Fecha</th>
				<th>Hora inicio</th>
				<th>Hora final</th>
				<th>Humedad inicial</th>
				<th>Humedad final</th>
				<th>Total litros</th>
			</tr>
		</thead>
		<tbody>
			{% for history in histories %}
			
				<tr>
					{# <td>{{ history.sector_id }}</td> #}
					  {% for sector in sectors %}
						{% if history.sector == sector %}
							<td>{{ sector.name }}</td>
							
						{% endif %}
					{% endfor %}
					
					<td>{{ history.date ? history.date|date('d-m-Y') }}</td>
					<td>{{ history.start_time ? history.start_time|date('H:i') }}</td>
					<td>{{ history.end_time ? history.end_time|date(' H:i') }}</td> 
					<td>{{ history.start_humidity }}</td>
					<td>{{ history.final_humidity }}</td>
					<td>{{ history.total_liters }}</td>
					 
				</tr>
			{% endfor %}
		</tbody>
	</table>
	
</div>

{% endblock %}

templates/history/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New History{% endblock %}

{% block body %}
    <h1>Create new History</h1>

    {{ include('history/_form.html.twig') }}

    <a href="{{ path('history_index') }}">back to list</a>
{% endblock %}

templates/history/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}History{% endblock %}

{% block body %}
    <h1>History</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ history.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ history.date ? history.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Start_time</th>
                <td>{{ history.startTime ? history.startTime|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End_time</th>
                <td>{{ history.endTime ? history.endTime|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Humidity_initial</th>
                <td>{{ history.humidityInitial }}</td>
            </tr>
            <tr>
                <th>Humidity_final</th>
                <td>{{ history.humidityFinal }}</td>
            </tr>
            <tr>
                <th>Total_liters</th>
                <td>{{ history.totalLiters }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('history_index') }}">back to list</a>

    <a href="{{ path('history_edit', {'id': history.id}) }}">edit</a>

    {{ include('history/_delete_form.html.twig') }}
{% endblock %}